//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppClient.MultiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MultiServiceReference.IMultiSvc")]
    public interface IMultiSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiSvc/Mul", ReplyAction="http://tempuri.org/IMultiSvc/MulResponse")]
        int Mul(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiSvc/Mul", ReplyAction="http://tempuri.org/IMultiSvc/MulResponse")]
        System.Threading.Tasks.Task<int> MulAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMultiSvcChannel : WebAppClient.MultiServiceReference.IMultiSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiSvcClient : System.ServiceModel.ClientBase<WebAppClient.MultiServiceReference.IMultiSvc>, WebAppClient.MultiServiceReference.IMultiSvc {
        
        public MultiSvcClient() {
        }
        
        public MultiSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MultiSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Mul(int a, int b) {
            return base.Channel.Mul(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int a, int b) {
            return base.Channel.MulAsync(a, b);
        }
    }
}
